### ISSUE TITLE
Support for Safari browser

### ISSUE THREAD

**Issue by anton-trunov** [cpitclaudel/academic-poster-template#1]
Thanks for sharing! This looks fantastic in Chrome 85.0.4183.102.

Here is what I see on macOS 10.15.6 "Catalina" using Safari 13.1.2 (just standard settings and no browser extensions, no zooming in or out).

![Screenshot 2020-09-16 at 11 56 44 AM](https://user-images.githubusercontent.com/2316541/93315437-bac8a480-f813-11ea-961e-bbead4089f52.png)

**Comment by cpitclaudel** [comment]
Thanks for testing it out!

I need to steal a Mac from a friend to investigate this :) I think it's a problem with Safari's CSS3 support.

**Comment by cpitclaudel** [comment]
I think this is fixed now :) https://github.com/cpitclaudel/academic-poster-template/commit/bc50c95704d43f4547621c4be8b9f4bb684c1fa1

**Comment by anton-trunov** [comment]
Thanks a lot!
